AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template for Lambda functions

Resources:
  LambdaFunction1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://picsearch-lambdafunctions/lambda_function_1.zip
      MemorySize: 128
      Timeout: 120
      Handler: lf1.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - rekognition:*
                - es:*
              Resource: '*'
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:ListBucket
              Resource: arn:aws:s3:::photos-b2-bucket/*
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:DescribeLogGroups
                - logs:DescribeLogStreams
                - logs:PutLogEvents
                - logs:GetLogEvents
                - logs:FilterLogEvents
              Resource: arn:aws:logs:*:*:*
      SnapStart:
        ApplyOn: None
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: PhotoStoreBucket
            Events:
              - s3:ObjectCreated:*
      RuntimeManagementConfig: {}
  
  PhotoStoreBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  
  PhotoStorePolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: PhotoStoreBucket
      PolicyDocument:
        Statement:
          - Action: s3:*
            Effect: Deny
            Principal: '*'
            Resource:
              - arn:aws:s3:::PhotoStoreBucket/*
              - arn:aws:s3:::PhotoStoreBucket
            Condition:
              Bool:
                aws:SecureTransport: false

  LambdaFunction2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://picsearch-lambdafunctions/lambda_function_2.zip
      MemorySize: 128
      Timeout: 120
      Handler: lf2.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - lex:*
              - s3:*
              - es:*
            Resource: '*'
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:DescribeLogGroups
              - logs:DescribeLogStreams
              - logs:PutLogEvents
              - logs:GetLogEvents
              - logs:FilterLogEvents
            Resource: arn:aws:logs:*:*:*
      SnapStart:
        ApplyOn: None
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /search
            Method: GET
      RuntimeManagementConfig: {}