version: 0.2

env:
  variables:
    LAMBDA_BUCKET: "picsearch-lambdafunctions" 

phases:
  install:
    runtime-versions:
      python: 3.12
  
  pre_build:
    commands:
      - echo "Running pre-build commands..."

  build:
    commands:
      - ls
      - pwd
      - echo "Building Lambda function 1..."
      - cd lambdafunctions/LF1
      - pip install -r requirements.txt -t ./
      - zip -r ../lambda_function_1.zip *
      - aws s3 cp ../lambda_function_1.zip s3://$LAMBDA_BUCKET --output=text

      - echo "Building Lambda function 2"
      - cd ../LF2
      - pip install -r requirements.txt -t ./
      - zip -r ../lambda_function_2.zip *
      - aws s3 cp ../lambda_function_2.zip s3://$LAMBDA_BUCKET --output=text

artifacts:
  files:
    - lambda_function_1.zip
    - lambda_function_2.zip
    - otherscripts/deploy_lambdas.yml